### ISSUE TITLE
Mechanism and rake in event.xml are ignored

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#1075]
Even when an event is run without select, the "mech" and "rake" keys in event.xml get ignored. We have code that parses "mech" [here](https://github.com/usgs/shakemap/blob/master/shakelib/rupture/origin.py#L96) and "rake" [here](https://github.com/usgs/shakemap/blob/master/shakelib/rupture/origin.py#L108). So something seems to not be behaving as intended.

**Comment by cbworden** [comment]
I'll have a look and let you know ASAP.

**Comment by cbworden** [comment]
I believe this is fixed by #1076. Anything in the event specific model.conf or model_select.conf, or the profile-wide model.conf will override the values set in event.xml, but if those files don't set "mechanism", then the "rake" in event.xml will define the mechanism, or if "mech" is set, it will define the mechanism. The final fallback (if none of the above set the mechanism) is "ALL".
