### ISSUE TITLE
Help installing ShakeMap

### ISSUE THREAD

**Issue by SergioT59** [usgs/shakemap#1129]
Hello,
I'm using seiscomp under fedora24 that use python 2.7.
After have try to intall shakemap 4, I have understand then it do not work because it use python 3, and many error that gives to me by py.test, was given because python has different version.
Now I would like to install version 3.5 of shakemap, but I have not understand how do it.
Anybody can help me?
Regards,

Sergio

**Comment by emthompson-usgs** [comment]
The ShakeMap install process uses conda virtual environments so that it doesn't matter what other versions of python you have installed on the system.

**Comment by emthompson-usgs** [comment]
Also, ShakeMap 3.5 is no longer supported. If you want to install that, then you are on your own.

**Comment by cbworden** [comment]
As Eric said, the ShakeMap install process creates a unique virtual environment. Please see the wiki for installation instructions: https://github.com/usgs/shakemap/wiki

**Comment by SergioT59** [comment]
Hello Eric and Bruce,
First of all thanks for yours answers.
I  tried to install version 4 in my system, but I get, when I do py.test, many errors, over 1000.
I have read in manual 4, at chapt 4.2.1 Installation, that there is the possibility to conflict with  with python 2 as in my case, and I have thought that 3.5 was the best for me.

You think I need to install version 4 and correct the errors?

**Comment by SergioT59** [comment]
Hello Eric and Bruce,
First of all thanks for yours answers.
I  tried to install version 4 in my system, but I get, when I do py.test, many errors, over 1000.
I have read in manual 4, at chapt 4.2.1 Installation, that there is the possibility to conflict with  with python 2 as in my case, and I have thought that 3.5 was the best for me.

You think I need to install version 4 and correct the errors?

I have reinstalled shakemap 4.0 and I have some mistaken:
1) following the installing suggestion, (I haven't conda) I have istalled mamba and then run install.sh -d for shakemap.
restarting the computer, my system do not recognize the python2's path and seiscomp3 do not start for the error. After that I have comment the .bashrc rows that to that has path to mamba's python 3. All seiscomp's python scripts gets errors when they try to run.
What can I do?

**Comment by emthompson-usgs** [comment]
It would be better if you opened a new issue with a request for help on installing ShakeMap version 4. Since we are still on this ticket requesting support for v3, I'll just edit the title of this issue and re-open it I guess. 

I don't think we really have enough info to know what is happening on your system. 

I'm assuming you installed mamba using conda per the mamba [readme](https://github.com/mamba-org/mamba)? If so, how did you install conda? I'm confused because it sounds like you do not have conda installed. If you do not have conda installed, the installer script will try to install it for you. The installer script is not written in a way that will use mamba currently but it can be easily modified to do so. 

I suppose it is possible that something in that process installed a newer version of python which is now the one being found by seiscomp by default. I would be extremely surprised if you don't still have python 2 somewhere on your system. 

You can probably find your python 2 path with `which python2`. Please tell us what that command prints to the terminal. 

I don't use seiscomp so I don't know anything about it. But I would hope that there's a way to specify the python path, using the output of the previous step. 

Regarding the pytest errors, it would be nice if we can see that output, by copy/paste the terminal output into a comment on this issue, and wrap it in trippe back ticks ` so that it is well formatted. Like this:
```
your terminal output here
```

I think it is most likely that the install process did not work and so there's no reason to be running the unit tests until you get the install process complete. Please also include the terminal output of running
```
bash intsall.sh -d
```

**Comment by emthompson-usgs** [comment]
Also, regarding your comment about the manual in section 4.2.1: it does **not** state that there is a conflict with python 2. It just says that it runs in python 3 and that many systems still use python 2 (which is insane since python 3 was released 14 years ago!). The point of that section is to explain that conda helps avoid conflicts by using virtual environments. This allows you to keep python 2 or whatever else your system needs installed, and also use python 3 for shakemap. The whole point is to avoid dependency side effects when installing shakemap like the one that you describe here with seiscomp, but I think that since you have tried to avoid following the instructions, you have created the problem that we are trying to avoid.

**Comment by cbworden** [comment]
Note that if you activate the shakemap virtual environment, seiscomp will not run because the shakemap virtual environment uses python3. Thus, if you want to run both applications at the same time, you will need different terminals open, one for each application. Or you can switch back and forth by activating and deactivating the shakemap environment as needed.

Nothing in the install process should affect any installed software as everything goes into the shakemap virtual environment, so don't start trying to uninstall or reinstall anything related to seiscomp or python2.

You can see the shakemap environment by doing "conda info --envs". The asterisk will tell you which environment is active. You can then use "conda activate shakemap" to activate the shakemap environment or "conda deactivate" to deactivate it. Use "conda remove --name shakemap --all" to remove the environment and start again.

Using mamba rather then conda won't help you pass the tests. It just helps speed up one stage of the installation.

**Comment by SergioT59** [comment]
Ok,
following instruction I have installed shakemap 4.0. During installation it request me to set the environment PYTHONPATH that I have already set as /home/sysop/seiscomp3/lib/python
If I set again as /home/sysop/miniconda my seiscomp3 do not found python2 instructions but the python3, and goes on error

**Comment by SergioT59** [comment]
Well. I have download Miniconda3. When I start the installation it inform me with a warning.
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda3: /home/sysop/miniconda3
Do you wish the installer to initialize Miniconda3
by running conda init? [yes|no]
I have to proceed to install? if so, after that, how can I switch between python2 and python3?

**Comment by emthompson-usgs** [comment]
I'm confused: you closed this issue, does that mean that it is resolved?

I go through the shakemap install process very often and I have never had to specify the `PYTHONPATH` and I can't tell why this is happening based on the information you are providing. Can you please copy/paste your terminal output in a way that shows the commands you running and the resulting output? 

Also, for clarity, please wrap any terminal output in triple back ticks ` so that it is well formatted.

**Comment by SergioT59** [comment]
Sorry, I have do a mistake.
I didn't whant to close because I have not solve the installation. I didn't realize that pressing that button would end the conversation

**Comment by SergioT59** [comment]
![immagine](https://user-images.githubusercontent.com/34506667/118799525-1cf41080-b89f-11eb-85a0-1323016392db.png)
This when I install miniconda

**Comment by emthompson-usgs** [comment]
This isn't helpful because I don't see what you did to get to this screen. This should not happen if you are following the install instructions. Please do not insert screenshots of the terminal. I gave you instructions twice for how to copy/paste the terminal output as text. 

That said, I suspect that this is not an issue. You should be fine to leave `PYTHONPATH` pointing to your python2 location. On my system, where I install shakemap and run it frequently here is my `PYTHONPATH`:

```shell
$ echo $PYTHONPATH

$ 
```

You can see that it is empty/unset. If you simply follow the shakemap install instructions, and do NOT do anything else, I'm pretty sure this will work.

**Comment by cbworden** [comment]
This doesn't make sense to me, either. We need to see your full terminal output, including the commands you issue to get the output to have any chance of helping you.

Similar to Eric, my PYTHONPATH is set to a directory that doesn't even exist on my system, but I don't have this issue.

Are you following the install instructions in the wiki and running simply:

    ```$ bash install.sh```

or are you doing something else?

**Comment by SergioT59** [comment]
Ok, restart from top.
After download shakemap, I write ./install.sh

**Comment by emthompson-usgs** [comment]
What is the result?

**Comment by SergioT59** [comment]
meaningwhile it the installation write
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda3: /home/sysop/miniconda
Installing packages from conda-forge
. /etc/profile.d/conda.sh
Activate base virtual environment

and at the end write:
Successfully installed django-2.2.23 numpy-1.19.5 openquake.engine-3.12.0 psutil-5.6.7 pyshp-1.2.3 pyzmq-19.0.2 sqlparse-0.4.1
Installing shakemap...
Obtaining file:///home/sysop/shakemap_src
Installing collected packages: shakemap
  Running setup.py develop for shakemap
Successfully installed shakemap-4.0.2+403.g52ba06e
Type 'conda activate shakemap' to use this new virtual environment.

I have PYTHONPAT already set because is used from seiscomp

[sysop@server_seiscomp shakemap_src]$ echo $PYTHONPATH
/home/sysop/seiscomp3/lib/python

**Comment by emthompson-usgs** [comment]
Ok. If you do the next steps
```
conda activate shakemap
```
and then run the tests within the virtual environment, what happens?

**Comment by emthompson-usgs** [comment]
.... also it is difficult to distinguish between what you are writing vs what is terminal output. That is the purpose of wrapping the terminal output in code blocks. It makes it easier for us to understand what is happening, and it is not very difficult to do.

**Comment by SergioT59** [comment]
[sysop@server_seiscomp shakemap_src]$ conda activate shakemap
bash: conda: comando non trovato...
[sysop@server_seiscomp shakemap_src]$ 

I can try to copy all output!
Do you whant all output?

**Comment by emthompson-usgs** [comment]
Check the contents of your `.bashrc` file. The install script was supposed to put in a line like this:
```
. ~/miniconda/etc/profile.d/conda.sh
```
Do you have anything like that? It is possible that this won't get sourced until you start a fresh shell, so perhaps starting a new shell, then activate the shakemap environment will fix this if that line is present in the rc file.

**Comment by SergioT59** [comment]
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
. /etc/profile.d/condda.sh

. /etc/profile.d mean /etc or ./etc?

**Comment by emthompson-usgs** [comment]
Okay, this looks like a problem (assuming I can accurately interpret the information that is bizarrely formatted here). You need to add a line to source `conda.sh` when you start a shell. It should be located here:
```
~/miniconda/etc/profile.d/conda.sh
```
Please confirm that that it is present. If it is, then add this line to your `.bashrc` file:
```
. ~/miniconda/etc/profile.d/conda.sh
```
You may want to expand the `~` with the absolute path to your home directory, I'm not sure if that matters or not. 

@cbworden We should try to figure out why this isn't getting added to the `.bashrc` file. I think this could be a problem with the install script.

**Comment by SergioT59** [comment]
Yes, in ~/miniconda/etc/profile.d/ there is conda.sh.
Now I add in my .bashrc

**Comment by SergioT59** [comment]
Now I write source .bashrc
and then 
[code]conda activate shakemap[/code]

and the prompt has changed like
[sysop@server_seiscomp ~]$ conda activate shakemap
(shakemap) [sysop@server_seiscomp ~]$ 

and after

 (shakemap) [sysop@server_seiscomp ~]$ conda info --envs
# conda environments:
#
base                     /home/sysop/miniconda
shakemap              *  /home/sysop/miniconda/envs/shakemap

(shakemap) [sysop@server_seiscomp ~]$

**Comment by emthompson-usgs** [comment]
Ok. You can check a few things like running 
```
shake -h
```
to confirm that everything installed correctly, and if so, then run the unit tests.

**Comment by SergioT59** [comment]
(shakemap) [sysop@server_seiscomp ~]$ shake -h
Traceback (most recent call last):
  File "/home/sysop/miniconda/envs/shakemap/bin/shake", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/sysop/shakemap_src/bin/shake", line 86, in <module>
    _config_ = _get_config()
  File "/home/sysop/shakemap_src/bin/shake", line 36, in _get_config
    install_path, data_path = get_config_paths()
  File "/home/sysop/shakemap_src/shakemap/utils/config.py", line 79, in get_config_paths
    raise FileNotFoundError("Can't find a profile file: "
FileNotFoundError: Can't find a profile file: have you run sm_profile?
(shakemap) [sysop@server_seiscomp ~]$ 

Sorry, but how do you use to mark the commands?

**Comment by emthompson-usgs** [comment]
Oh right, I forgot you have to setup your profiles before `shake -h` will work. See the wiki here:
https://github.com/usgs/shakemap/wiki/Profile-Setup
That said, I think tests will run without the profile setup so you can do that:
https://github.com/usgs/shakemap/wiki/testing

You wrap the text in three back ticks (three of these: `) to format command blocks. You can use a single back tick for in-line commands.

**Comment by SergioT59** [comment]
Ok, for now many thanks.
Now I try to understand the profile and create them.
Please, can you waiting me to build this service?

**Comment by emthompson-usgs** [comment]
I would prefer to close this issue. If you have additional problems with the profiles, feel free to open a new issue and we will respond to that.
