### ISSUE TITLE
Installing on Fedora33

### ISSUE THREAD

**Issue by SergioT59** [usgs/shakemap#1143]
Hi all,
now I had to install shakemap on fedora 33. but when I run install.sh, goes on error:

     Solving environment: | ./install.sh: riga 201: 21379 Ucciso                  "$CONDA_EXE" $_CE_M $_CE_CONDA "$cmd" "$@"
     Failed to create conda environment.  Resolve any conflicts, then try again.

My python is 3.9.5

Sergio

**Comment by SergioT59** [comment]
Hi again,
there is anybody that can help me?

**Comment by emthompson-usgs** [comment]
Please be patient. Your issues are not the only things we have to deal with. @cbworden just made some changes to the code to resolve some other reported issues. I have tried to reproduce your problem but I have not been able to yet. Note that as I explained to you previously in an earlier issue you reported, your version of python doesn't matter because we use conda virtual environments and install a separate version of python for ShakeMap, which is python 3.7. 

The problem you are having is with conda not being able to find compatible dependencies. One of manhy possible solutions may be to simply increment the python version from 3.7 to 3.8 but I have not tested that yet.

**Comment by SergioT59** [comment]
Thaks for your answer, now I can waiting for your message
By the way, is it possible that the memory is insufficient?

**Comment by emthompson-usgs** [comment]
Yes, that is possible. I have heard from others that when this happens, switching from conda to mamba can resolve it. You would have to install mamba yourself (https://mamba.readthedocs.io/en/latest/) and then modify the install.sh file to use it.

**Comment by SergioT59** [comment]
Hello Eric,
yes, the problem is the small memory.
I have only 3Gb of memory and 1.8 Gb of swap memory.
I have created and mount an other swap memory (in ssd drive) of 16Gb and now all is installed.
The only inconvenience is that I had to set .bashrc to complete the installation inserting the rows for conda's setup

    __conda_setup="$('/home/sysop/miniconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
    export PATH="/home/sysop/miniconda/bin:$PATH"    
    if [ -f "/home/sysop/miniconda/etc/profile.d/conda.sh" ]; then
      . "/home/sysop/miniconda/etc/profile.d/conda.sh"
    else
      export PATH="/home/sysop/miniconda/bin:$PATH"
    fi

Best regards

Sergio

**Comment by emthompson-usgs** [comment]
Okay, glad that solved it. Thanks for letting us know.
