### ISSUE TITLE
how to add a new gmpe

### ISSUE THREAD

**Issue by krokodeilakias** [usgs/shakemap#1155]
Hi,
 Could someone point me to instructions on how to implement a new GMPE to ShakeMap 4? I would like to add a GMPE which has just been put in OpenQuake git master (https://docs.openquake.org/oq-engine/master/openquake.hazardlib.gsim.html#module-openquake.hazardlib.gsim.boore_2020).

Thanks in advance,
Petros

**Comment by cbworden** [comment]
At the moment OpenQuake is undergoing major revisions on a near-daily basis and is not compatible with ShakeMap. When things settle down, or they issue a new tagged release, we will adapt our code and will be able to take advantage of any new developments. Until then, we are stuck with their March 22 release (3.11.3). I'll keep this issue open and try to notify you when we have any progress to report.

**Comment by krokodeilakias** [comment]
Thanks again, I'll remain.

**Comment by cbworden** [comment]
If you grab the latest version from our repository:
```
> git clone https://github.com/usgs/shakemap.git shakemap_src
```
and run the install script right away, you should have a working version with the latest version of OpenQuake. I can't say how long it will be until the OQ folks change something that breaks ShakeMap again, so you should probably do the install as soon as possible so you pull a compatible version of their repo.

If this is your first install, just follow the instructions in the wiki: https://github.com/usgs/shakemap/wiki/Installation except use the line above to clone the repo instead of the one given in the wiki. You don't want branch 4.0.4.

If you have an existing install of ShakeMap that you're upgrading you'll want to do:
```
> git pull --rebase origin master
> bash install.sh
```
I added the new Boore 2020 GMPE to ShakeMap, so you'll want to copy `modules.conf` and `gmpe_sets.conf` from `.../shakemap_src/shakemap/data` to wherever you have your config files -- probably your starting in your home directory `~/shakemap_profiles/default/install/config`. You can either use `Boore20` as the `gmpe` in `model.conf` or use `Bea20` as part of a new GMPE set.

Good luck. This version of ShakeMap is not well tested yet.

**Comment by krokodeilakias** [comment]
Thanks for your prompt help. I upgraded as you suggested and run a successful test with the new gmpe. I'll go through some more tests and let you know in case of problem.
Thanks again.
