### ISSUE TITLE
File for fixed Vs30 values

### ISSUE THREAD

**Issue by ptrian** [usgs/shakemap#1184]
I'd like to define some fixed values of Vs30 at specific points. Following the manual's instructions, I created a file containing rows of latitude, longitude, Vs30 and facility's identifier and modified `prediction_location` in _model.conf_:

`40.632485829399997 22.867039588600001 270 HI`
`40.635187924500002 22.866993910700000 270 HI`
`40.606331902900003 22.959676832900001 600 HI`
`40.606363783900001 22.963222327400000 600 HI`
`...`

However, when shakemap runs, I receive the following exception error:

`Exception: mapping module can only operate on gridded data, not sets of points`
`Stack Trace:   File "/opt/SHAKE/shakemap_src/bin/shake", line 323, in main`
`    obj.execute()`
`  File "/opt/SHAKE/shakemap_src/shakemap/coremods/mapping.py", line 111, in execute`
`    raise NotImplementedError('mapping module can only operate on '`

Is the use of gridded file mandatory or text files can be used as well? Is there a step-by-step guide to create a grd file appropriate for this case?
Thanks in advance.

---
- Version: 4.0.2+475.gc126b8d3
 full-revisionid: c126b8d3fd43154877ba4a9fdef778fc59e2bf37
 dirty: False
 date: 2021-07-22T15:43:53-0600

- SMP Debian 4.9.272-2 (2021-07-19)
- conda 4.8.3

**Comment by cbworden** [comment]
Sorry, you cannot do what you are trying to do with ShakeMap. If you create a set of facilities or points for ShakeMap, then the "model" module will only compute ground motion values for those specific locations. After that, there is no way to create a grid or map of the values. You just have that set of points as output.

It is not possible to use specific Vs30 values at certain sites to create a grid because those sites would be inconsistent with the Vs30 grid as a whole, creating discontinuities, and would result in ShakeMap ground motions not matching the input values. We have been through this many times with many users, but there is just no way to do it. If you want to use custom Vs30 values, you have to create a custom Vs30 grid. And even then, your measured values are mostly not going to be exactly on grid points so they'll be interpolated.

**Comment by ptrian** [comment]
Thanks Bruce for the detailed answer. However, it still remains unclear to me why custom Vs30 values can't be used alongside with the global Vs30 ones. In Heath et al. (_2020, Earthquake Spectra_) (which I saw after posting here), you describe a procedure of constructing a hybrid Vs30 map by using a regional Vs30 map inserted into the global one.
I didn't go through the programs in ScienceBase, but I wonder if the same procedure could be followed in order to use the existing hybrid map of Greece with a more detailed map of local Vs30 values. In that case, the current hybrid map will be assumed as global and the custom Vs30 values as the regional.
I guess that the output should have to be smoothed, since the resolution of local (=now regional) map is finer, but this might seem OK. Do you think that for a very small area with a coarser grid, the smoothed values will only slightly differ from the global ones and the whole attempt is more or less pointless?
I hope all the above make sense to you, thanks once again.

**Comment by emthompson-usgs** [comment]
@ptrian What you are describing is what @cbworden meant by "create a custom Vs30 grid." The process of constructing a Vs30 map (whether it is based on geology, slope, Vs30 values, or whatever) is not something that the ShakeMap software supports. So you can go through that process for your region of interest, and then provide the map as an input to ShakeMap. But you can't provide point Vs30 measurements and then expect ShakeMap to use those points in constructing a map.

**Comment by ptrian** [comment]
OK, now I get it. Thanks again.
