### ISSUE TITLE
UnboundLocalError: local variable 'df' referenced before assignment

### ISSUE THREAD

**Issue by dwilson1988** [usgs/shakemap#1251]
When running sm_create, I'm periodically getting an exception that originates in https://github.com/usgs/shakemap/blob/f23f1aeb252670b5eee25fd3529a78b7ffacd666/shakemap/coremods/dyfi.py#L152

When looking at the code, you can see there's no variable named "df" so that's the source of this.

An easy way to reproduce this error would be to run `sm_create -f usb000sq07`. I get the following traceback:

```running command: sm_create -f usb000sq07
Event usb000sq07 has no ShakeMap product, but does have DYFI. Downloading that data.
Traceback (most recent call last):
  File \"/opt/conda/envs/shakemap/bin/sm_create\", line 7, in \u003cmodule\u003e"
    exec(compile(f.read(), __file__, 'exec'))"
  File \"/root/shakemap_src/bin/sm_create\", line 619, in \u003cmodule\u003e"
    main(pargs)"
  File \"/root/shakemap_src/bin/sm_create\", line 378, in main"
    dataframe, msg = _get_dyfi_dataframe(detail)"
  File \"/root/shakemap_src/shakemap/coremods/dyfi.py\", line 112, in _get_dyfi_dataframe"
    df, msg = _parse_dyfi_detail(detail, min_nresp)"
  File \"/root/shakemap_src/shakemap/coremods/dyfi.py\", line 152, in _parse_dyfi_detail"
    if not len(df):"
UnboundLocalError: local variable 'df' referenced before assignment"
```

I'm assuming the intent was to check one of the other two dataframes created, but I'm not sure what the best fix is. I'm happy to submit a PR, but I'd need some guidance on what the correct behavior is.

**Comment by emthompson-usgs** [comment]
Thanks for this bug report! It looks like this bug was created about a year ago in [this](https://github.com/usgs/shakemap/commit/fdd1f2a29984573473838c3c3ea893128df8551e#diff-1ccb019c112ebdfb3e7f4099f9f2b44461d6eaba8bdafc584252f49b9f745c5f) pull request. The intent was to only use the 1 km DYFI data, so we essentially need to just change `df` to `df_1k`. 

Unfortunately, things are a bit complicated right now because we are in the process of moving the code to gitlab. We have not yet been able to make that repo public yet, and that is where all new changes need to be made. So someone within the USGS will need to make this fix (@cbworden, @vinceq-usgs, or me).

**Comment by cbworden** [comment]
This appears fixed. Closing.
