### ISSUE TITLE
Write code to fix faulty fault files

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#502]
...or at least handle errors cleanly

**Comment by mhearne-usgs** [comment]
Is a fault like this fixable? https://earthquake.usgs.gov/earthquakes/eventpage/official20041226005853450_30#shakemap

**Comment by emthompson-usgs** [comment]
I believe that there is nothing wrong with that specification because it has a horizontal top edge and bottom edge. It just can't be coerced into a QuadRupture so the distance calculations will be relatively slow. The error we get with the `get_rupture` method is this line:
https://github.com/usgs/shakemap/blob/master/shakelib/rupture/factory.py#L308
So the problem is that the vertices start on the bottom edge and loop up along the top edge. I think the algorithm for fix this is:

1. Drop the last point (which is the first one repeated),
2. Reverse the order of the remaining points, and
3. Append the (updated) first point. 

I did this manually and attached the result and it seems to work.

Also, this is an Atlas event and the rupture model probably needs to be updated to use a published inversion result (this one is just based on the aftershock distribution). 

[NEIC04_fault_fixed.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57b62ecf57c2e70e00c84f45/125516c66e82c728ace21e0d46c6b1b300d2d79689e8aa4fb062f69d314323316546b3397f8fe62bab0021435a594ff8435c0911f9f88a2ef4e73f748a5c0fe9d86e5f7dd42103eee9dc4be05ce36ade0d97bcae8b4bcae93827e28b8e4b3c1c011988fb4f78.txt)
