### ISSUE TITLE
Allow for some sort of configuration for dyfi module

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#518]
Currently just going to set minimum number of responses to 3.

**Comment by mhearne-usgs** [comment]
Also perhaps allow users to specify which geocoded file they prefer (1 or 10 km)

**Comment by cbworden** [comment]
This seems resolved, or at least there is no demand for it any longer. Module returns 1 km DYFI if available, otherwise 10 km file is returned. 3 response minimum is reasonable, and we now get uncertainties with each grid, so we can control DYFI's impact on the maps. I'm closing this until we come up with something specific we want to configure.
