### ISSUE TITLE
Units in uncertainty.xml

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#523]
... appear to be wrong. How should we give the units? Maybe "std(ln(%g))" forPGA? I'm not sure.

**Comment by mhearne-usgs** [comment]
Tell me what units you want and I can fix it...

**Comment by cbworden** [comment]
I think this module is buggier than we thought. Why, for instance, does the uncertainty grid get the "mean" from the imtdict, rather than the 'std'?

FWIW, it looks like the module exponentiates the grids and changes the units accordingly, but the question is, what do we want it to do for uncertainty? The current v3.5 uncertainty.xml leaves them in log space, which makes sense to me.
