### ISSUE TITLE
Comparison tool

### ISSUE THREAD

**Issue by cbworden** [usgs/shakemap#572]
Some kind of tool to compare v3.5 vs. v4.

**Comment by emthompson-usgs** [comment]
Can we be more specific about what this is supposed to be? Is this to make difference and ratio maps? Or is this to do some kind of leave-one-out cross validation? I'd prefer it to be the former since that is something that is more routine, while the latter is rather open-ended and comes with a lot of associated subtle issues.

**Comment by emthompson-usgs** [comment]
Should inputs be a grid.xml from shakemap 3.5 and 4.0? Or should it just be shakemap 3.5 and then run shakemap 4.0, allowing for options to select the GMPE?

**Comment by cbworden** [comment]
I think we need both things, but in the near term we could just compare output grids with ratios and differences. It might be nice to do the leave-one-out thing for a selected set of maps and see how v4 performs, which could lead to some kind of writeup either as a paper or as part of the docs. But we can do that later. For now, I think people are just going to want to see how the maps differ -- and it might help us understand where the differences are coming from.
