### ISSUE TITLE
Re-do pyshake library structure

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#65]
Roughly organize code currently in shakelib into pyshake sub-packages named after the top level program (grind, transfer, etc.) which *primarily* uses that code.  These sub-packages will then contain the *functions* corresponding to the top level program.  Thus:

pyshake/transfer - transferlib.py, ftpsender.py, pdlsender.py, etc.
pyshake/grind - grind.py, source.py, fault.py, distance.py, etc.
pyshake/misc - other stuff we can't categorize...

There will also be a data directory where non-installation specific data files will go.

pyshake/data - configspec.ini, others.

The configuration code should live in the pyshake package, so:

pyshake/conf.py

Also, we will need a module at the same level called finder.py, which has a function like this:

def getDataDir():
  myfolder,myname = os.path.split(__file__)
  datadir = os.path.join(myfolder,'..','data')
  return datadir

This is for use by the top-level programs (grind, transfer, etc.) which wouldn't otherwise know the path to this data directory.

**Comment by emthompson-usgs** [comment]
I think we've refactored twice since this issue was created. To update, here is the current basic structure (we've also renamed the repository from pyshake to shakemap): 

Scripts will live in the base directory and generally do not have the .py extension. Current examples are: 
setup.py
setup_env.sh
makedocs.py
mkfault
mkscenariogrids
mkinputdir

The main packages are: 
shakemap/genex
shakemap/grind
shakemap/mapping
shakemap/transfer
shakemap/utils

We also have a 'gmice' package at this level, but we expect it to be removed since OQ will support GMICE. 

Currently, the most mature package is 'grind', which has the following structure: 
shakemap/grind/conversions/imc/beyer_bommer_2006.py
shakemap/grind/conversions/imt/bommer_alarcon_2006.py
shakemap/grind/conversions/imt/newmark_hall_1982.py
shakemap/grind/correlation/boore_2003.py
shakemap/grind/correlation/goda_atkinson_2010.py
shakemap/grind/data/ps2ff
shakemap/grind/directivity/bayless2013.py
shakemap/grind/directivity/rowshandel2013.py
shakemap/grind/distance.py
shakemap/grind/fault.py
shakemap/grind/gmpe2shakemap.py
shakemap/grind/multigmpe.py
shakemap/grind/sites.py
shakemap/grind/source.py
shakemap/grind/station.py
shakemap/grind/zoneconfig.py

This basic structure is generally mirrored in the 'tests' directory. Test coverage in 'grind' is generally pretty high (~75%). Some of the packages/modules are not complete and so do not have tests yet (e.g., correlation, station, zoneconfig).
