### ISSUE TITLE
Zero bias?

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#697]
We need to run usp000juhz in SM4 and check the bias calculation. According to a report from a regional operator, it is zero, but I believe that it should not be zero since there is data for this event.

**Comment by cbworden** [comment]
I think the issue here was that the magnitude was larger than the threshold for computing a bias unless a finite fault is supplied. The idea is that for large events/ruptures, it's very hard to know how far a station is from the rupture, and so it's hard to get an accurate residual for the bias. The parameter is user configurable, but I think the event is a 7.8 and the default configuration has the threshold at 7.7.

**Comment by cbworden** [comment]
Yes, that was the issue. I ran the event with a higher bias cutoff threshold and it computed a bias
