### ISSUE TITLE
errors in running example event ci3144585

### ISSUE THREAD

**Issue by dynaryu** [usgs/shakemap#713]
When I tried the example event ci3144585 in the wiki, I've got the following errors: 

(shakemap) ~/Projects/shakemap_src$ shake ci3144585 assemble
INFO -- 2018-07-27 09:49:21 -- shake.main -- Running command assemble
Please enter a comment for this version.
comment: testing
ERROR -- 2018-07-27 09:49:24 -- config.file_type -- file '/Users/hyeuk/shakemap_profiles/default/install/data/vs30/CA_vs30.grd' is not a valid file
ERROR -- 2018-07-27 09:49:24 -- config.config_error -- The "vs30file" key in the section "data" failed validation
CRITICAL -- 2018-07-27 09:49:24 -- shake.main -- 
Earthquake: M6.7 1km NNW of Reseda, CA
Host: Hyeuks-MacBook-Pro.local
Event ID: ci3144585
Exception: There was 1 error in configuration.
Stack Trace:   File "/Users/hyeuk/Projects/shakemap_src/bin/shake", line 249, in main
    obj.execute()
  File "/Users/hyeuk/Projects/shakemap_src/shakemap/coremods/assemble.py", line 150, in execute
    config_error(global_config, results)
  File "/Users/hyeuk/Projects/shakemap_src/shakemap/utils/config.py", line 215, in config_error
    'error' if errs == 1 else 'errors'))

I noticed that the CA_vs30.grd does not exist in the path defined in the model.conf, but in the testing data directory. Not sure whether I did not follow the steps correctly, or something wrong with instruction. The script ran okay after I copied the file to the path.

(shakemap) ~/Projects/shakemap_src$ shake ci3144585 mapping
INFO -- 2018-07-27 10:25:59 -- shake.main -- Running command mapping
ERROR -- 2018-07-27 10:25:59 -- config.file_type -- file '/Users/hyeuk/shakemap_profiles/default/data/topo/topo_30sec.grd' is not a valid file
ERROR -- 2018-07-27 10:25:59 -- config.config_error -- The following section was missing: 
CRITICAL -- 2018-07-27 10:25:59 -- shake.main -- 
Earthquake: M6.7 1km NNW of Reseda, CA
Host: Hyeuks-MacBook-Pro.local
Event ID: ci3144585
Exception: There was 1 error in configuration.
Stack Trace:   File "/Users/hyeuk/Projects/shakemap_src/bin/shake", line 249, in main
    obj.execute()
  File "/Users/hyeuk/Projects/shakemap_src/shakemap/coremods/mapping.py", line 184, in execute
    config_error(config, results)
  File "/Users/hyeuk/Projects/shakemap_src/shakemap/utils/config.py", line 215, in config_error
    'error' if errs == 1 else 'errors'))

Similarly, it ran okay after I copied the top_30sec.grd to the path defined in the model.conf.

**Comment by cbworden** [comment]
Hi,

The default configs are set up to work with the tests, which have some supporting data files already loaded (i.e., they come with the repository). When you make a new profile, the default configs are copied over, but there is no guarantee that the paths are valid (since you can name your profile anything and, thus, the path can go anywhere). Once the user makes a profile it is incumbent upon him/her to make sure that the paths in the configs point to real data files. For some of the mapping files found in products.conf, one can likely make use of the ones that come with the repo, but for things like the topography or vs30 (in model.conf), the expectation is that the user will want to customize these things for their region.

I’ll look into the default behavior of sm_profile, since if the user gets the global topo and vs30 files, the configs should point to those. But you’ll still need to go through the configs and make sure everything else is set correctly.

Bruce

**Comment by dynaryu** [comment]
Thanks for your comments, Bruce. I understand that user should check the path in any case, but I'd like to point out that instructions in the wiki for the example event should be corrected so that user should get the results without seeing the error messages. Any required changes should be included in the instructions.
