### ISSUE TITLE
Remove defaults channel from install script

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#804]
Based on this thread:
https://github.com/conda-forge/scipy-feedstock/issues/86

It seems like it would be safer for us to depend on conda-forge for everything if we can.

**Comment by emthompson-usgs** [comment]
My understanding is that we did this a long time ago and is the main reason we are no longer using the environment.yml files (because if you use those, it is impossible to suppress the default channel). Are you getting packages installed from the default channel? I just checked the environment on my system (which was installed less than a week ago) and no package came from defaults.
