### ISSUE TITLE
us10004u1y event products are very large

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#838]
This may have been dealt with by avoiding events in the ocean, or perhaps by making resolutions coarser...

**Comment by emthompson-usgs** [comment]
Yes, that event has >3M grid points so the event was not run with the code after my #825 PR resolved issue #822. Also, I'm not understanding why v4 shakemap products are getting sent to dev without the "_sm" string appended to the product code. Because of this, it is stomping on the v3 products and so we can no longer compare them.
