### ISSUE TITLE
Error handling with reading station data

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#860]
With sm_create, there can be errors in the station data imported from old shakemaps which causes the data to be ignored in the model coremod. Basically no error is given though and we need to trap for this when we run atlas so we can be sure to fix the data.

**Comment by cbworden** [comment]
@mhearne-usgs is this still an issue? If it is and we have an example, I can look into it.

**Comment by mhearne-usgs** [comment]
@emthompson-usgs Do we have any examples of this? If we don't, then I suggest we close it until/unless it pops up again.

**Comment by emthompson-usgs** [comment]
Hmm, are you saying I should have done a better job documenting the errors 4 month ago? I tried to reproduce the problem (after updating to the latest version of the code just now) with the following:
```
sm_create usp000d3mb
shake usp000d3mb assemble -c '' model mapping plotregr info
```
There is some strange behavior:
  - intensity.jpg and pga.jpg show the station locations, but they have no fill.
  - info.json has null for the bias field, but also indicates that there are 791 seismic stations.
  - Regression plots do now show any data.

So it is like the data is getting all read in but is not getting used. I also see that in the info.json, it says that 791 stations are getting flagged. Note that in my call to `shake` I did not get any warning or error messages that indicated anything was amiss. I suspect that the stations are getting flagged for some spurious reason. 

![intensity](https://user-images.githubusercontent.com/15928870/54160182-7dac7680-4414-11e9-8638-d0596e0674b0.jpg)
![pga_regr](https://user-images.githubusercontent.com/15928870/54160197-869d4800-4414-11e9-97c3-432ee76d58cb.png)
![pga](https://user-images.githubusercontent.com/15928870/54160214-91f07380-4414-11e9-8f4b-202c17f8bbec.jpg)

**Comment by emthompson-usgs** [comment]
Looks there are two different station flags: 
  - `flag: "UnknownOrientation,UnknownOrientation,0,Outlier"`
  - `flag: "G,UnknownOrientation,0,Outlier"`

**Comment by cbworden** [comment]
This is the result of having only one channel and its channel code being the same as the station code. ShakeMap 3.5 could handle this input, but ShakeMap 4 is more fussy. We can either reprocess the data and give three channels with proper channel names, or we can simply change the channel "name" in the JSON to "UNK", in which case ShakeMap will assume it is horizontal, and not worry about the absence of another horizontal channel. sm_create should probably look for this condition (since it seems to happen for some of the Atlas events) and fix it on the fly, while notifying the user that it might be a good idea to reprocess this data.

**Comment by cbworden** [comment]
I just grabbed and ran this event and the problem seems fixed. The stations all have three channels: H1, H2, and Z. So we've either reprocessed everything, or we've fixed the inputs. In any event, the Atlas is out there and I think we've caught all (?) of these oddball events. If any more crop up, we can treat them on a case by case basis. But this isn't really something we can fix anymore.
