### ISSUE TITLE
Invalid MMI_pred_phi values for custom GMICE

### ISSUE THREAD

**Issue by dhowell-sed** [usgs/shakemap#969]
As we discussed via email, we are experiencing the following issue when running a model with a custom GMICE:

In shakemap.coremods.model.ModelModule._deriveMMIFromIMTs(), an assumed value for the inter-event standard deviation of 0.4 is used when only the total standard deviation is available. However, when using our own GMICE, this value sometimes generates an invalid intra-event standard deviation (phi) for MMI. For example, in ModelModule._deriveMMIFromIMTs() :

```
    Line 1043: df['MMI' + '_pred_phi'] = np.sqrt(
    Line 1044:      pstddev[0]**2 - tau_guess**2)
```

(pstddev[0] ** 2 - tau_guess ** 2) is sometimes negative since the total variance is less than the guess for the inter-event variance.

If possible, we would like to find a way to produce valid (non-NaN) values for phi in these cases where our custom GMICE/GMPE combination only supports uncertainties of type 'TOTAL'.

Thanks,
Dorran

**Comment by cbworden** [comment]
Thanks for the bug report. My intent is to make "tau_guess" a multiplier so that the phi value can never be negative. After looking at a few GMPEs, I think a value of 0.55 is reasonable. Thus if we only know sigma:

tau = 0.55 * sigma
phi = sqrt(sigma**2 - tau**2) = sqrt((1 - 0.3025) * sigma**2) = sqrt(0.6975 * sigma**2)

So phi is always positive and bigger than tau, with about a 70/30 contribution to the total sigma, which is more or less consistent with the GMPEs I've looked at. Give or take.

I'll probably push the revised code to the master repo tomorrow unless anyone has any major objections.

**Comment by cbworden** [comment]
I've pushed the changes discussed above to the repo. You can get the latest code and try it out. Let me know if you encounter any problems. In the meantime, I'm going to close this issue.

**Comment by dhowell-sed** [comment]
Hi Bruce,

I pulled the latest code and this seems to have fixed the above bug.

Thanks for the quick turnaround!
