### ISSUE TITLE
Add your own coastline

### ISSUE THREAD

**Issue by tgoded** [usgs/shakemap#998]
Hi,

We would like to add our own coastline in ShakeMap. I have added a path for coasts, lakes and oceans in products.conf (see below). However, shakemap is still creating the maps using the default coastline. What else needs to be changed to use our own? Would the contour filter size be affecting too? (I understand it's a smoothing, is that correct?)
I have also noticed that with this configuration it creates MMI values on the sea. Why is that?

Thank you very much and best regards

# ###########################################################################
# This configuration file provides a common location for parameters
# that affect the way shake modules make their products. The root element
# is "products" and the next level tags correspond to modules
# ###########################################################################
[products]
  # #########################################################################
  # The contour module makes contour files in GeoJSON format.
  # #########################################################################
  [[ contour ]]
    # #########################################################################
    # filter_size is an integer filter used to determine contour smoothing. See:
    # https://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.ndimage.filters.median_filter.html
    # Note: this parameter will also be used by mapping to make the contour maps.
    # #########################################################################
    filter_size = 10
  # #########################################################################
  # The mapping module makes basic maps.
  # #########################################################################
  [[ mapping ]]
    # #######################################################################
    # operator is a string printed into the title on the maps, as in
    # "USGS ShakeMap..." where "USGS" is the operator.
    # #######################################################################
    operator = USGS

    # #######################################################################
    # The layers below specify the paths to the data files for the
    # various geographic features. In the paths, the <INSTALL_DIR> and 
    # <DATA_DIR> macros will be replaced with the install path and data
    # path, respectively, of the user's current profile. If you have 
    # multiple profiles but only want to have one set of data files, 
    # an absolute path can be used.
    # #######################################################################
    [[[ layers ]]]
      #coasts = <INSTALL_DIR>/data/mapping/ne_10m_coastline.shp
      #oceans = <INSTALL_DIR>/data/mapping/ne_10m_ocean.shp
      lowres_oceans = <INSTALL_DIR>/data/mapping/ne_110m_ocean.shp
      #lakes = <INSTALL_DIR>/data/mapping/ne_10m_lakes.shp
      countries = <INSTALL_DIR>/data/mapping/ne_10m_admin_0_countries.shp
      states = <INSTALL_DIR>/data/mapping/ne_10m_admin_1_states_provinces.shp
      topography = /home/tatiana/shakemap_data/topo/topo_30sec.grd
      cities = <INSTALL_DIR>/data/mapping/cities1000.txt
	  #coasts = <INSTALL_DIR>/data/mapping/NEW_ZEALAND/coastline.shp
	  #oceans = <INSTALL_DIR>/data/mapping/NEW_ZEALAND/lakes.shp
	  #lakes = <INSTALL_DIR>/data/mapping/NEW_ZEALAND/ocean.shp
	  coasts = /home/tatiana/shakemap_profiles/default/install/data/mapping/NEW_ZEALAND/coastline.shp
	  oceans = /home/tatiana/shakemap_profiles/default/install/data/mapping/NEW_ZEALAND/lakes.shp
	  lakes = /home/tatiana/shakemap_profiles/default/install/data/mapping/NEW_ZEALAND/ocean.shp

**Comment by cbworden** [comment]
Hi Tatiana,
I'm not sure what version of code you are running, but most of those layers are no longer options in products.conf and will generate errors in newer version of the program. We removed the code that allowed the configuration of coastlines, lakes, oceans, etc., because it was a massive maintenance headache. All of those features are now drawn from the Natural Earth database which, yes, is not 100% accurate everywhere, but has the advantage of not requiring us to diagnose random problems with a million different shape files.

Going forward, the only valid parameters under [[[ layers ]]] are "topography", "faults", and "roads". To use something other than the NE files for other features, you would have to find where cartopy stashes them on your system and replace them. That might work, I don't know, I haven't tried it.

The contour filter size only affects the smoothing of the ground motion parameters when they are contoured for plotting. It does not affect any geographic features.
